version: "3.8"

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DB_NAME}
    networks:
      - postgres-network
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=avaliai.settings
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - SOCIAL_AUTH_SUAP_KEY=${SOCIAL_AUTH_SUAP_KEY}
      - SOCIAL_AUTH_SUAP_SECRET=${SOCIAL_AUTH_SUAP_SECRET}
      - URL_REDIRECT=${URL_REDIRECT}
      - AI_API_BASE_URL=${AI_API_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network