# Generated by Django 5.1.7 on 2025-04-02 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_answer_text_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
