# Generated by Django 5.1.7 on 2025-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='was_generated_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
