# Generated by Django 5.1.7 on 2025-07-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
